# Generated by Django 5.1.7 on 2025-04-02 03:23
from django.db import migrations
from danbooru.models import Post


def create_post_index( apps, schema_editor ):
    if not Post._index.exists():
        Post.init()

def delete_post_index( apps, schema_editor ):
    if not Post._index.exists():
        Post.init()


class Migration( migrations.Migration ):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython( create_post_index, delete_post_index ),
    ]
